layout_spectrum: 0.5788531
color:
  saturation: 1
  lightness: 0.7121513
  brandStrength: 0.4121864
  brandColors:
    - '#280C28'
    - '#774B4B'
    - '#BD9A7F'
    - '#D8BDA2'
    - '#FCFCFB'
  rhythmicContrast: 0.7150851
typography_spectrum: 0.1236559
name: 'Spencer King: Comedian'
